### ISSUE TITLE
npm build is failing

### ISSUE THREAD

**Issue by Mr-Black-Dahlia** [NickBolles/vulgar#1]
**Note: for support questions, please use one of these channels:** [Chat: VulgarDisplayOf2^2.slack](http://www.davidniciforovic.com/wp-login.php?action=slack-invitation) or [Twitter: @datatype_void](https://twitter.com/datatype_void)

- **I'm submitting a ... **

  [ X] bug report

  [ ] feature request

  [ ] question about the decisions made in the repository

- **Do you want to request a _feature_ or report a _bug_?**
A Bug
- **What is the current behavior?**
npm run build is failing
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
- <https://plnkr.co>, <https://codepen.io>, or similar.
1. git clone nb/materialize
2. npm install
3. npm run build
- **What is the expected behavior?**
Finish the build
- **Please tell us about your environment:**
Windows 10 x64, everything is installed and installed to latest.

Error in question:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.10
3 info using node@v6.9.5
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle vulgar@2.0.4~prebuild: vulgar@2.0.4
6 silly lifecycle vulgar@2.0.4~prebuild: no script for prebuild, continuing
7 info lifecycle vulgar@2.0.4~build: vulgar@2.0.4
8 verbose lifecycle vulgar@2.0.4~build: unsafe-perm in lifecycle true
9 verbose lifecycle vulgar@2.0.4~build: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\DPANtv\Desktop\ang2\test\vulgar\node_modules\.bin;C:\python27_x64\;C:\python27_x64\Scripts;C:\Program Files (x86)\ActiveState Komodo Edit 9\;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Kensington\TrackballWorks;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin;C:\Program Files\Git\cmd;C:\MAMP\bin\php\php5.5.24;C:\ProgramData\ComposerSetup\bin;C:\Program Files\nodejs\;C:\python27_x64\;C:\python27_x64\Scripts;C:\Program Files (x86)\ActiveState Komodo Edit 9\;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Kensington\TrackballWorks;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin;C:\Program Files\Git\cmd;C:\MAMP\bin\php\php5.5.24;C:\ProgramData\ComposerSetup\bin;C:\Program Files (x86)\Skype\Phone\;C:\python27_x64;C:\Users\DPANtv\AppData\Local\Microsoft\WindowsApps;C:\Users\DPANtv\AppData\Local\atom\bin;C:\Users\DPANtv\AppData\Roaming\npm;C:\Program Files (x86)\Microsoft VS Code\bin
10 verbose lifecycle vulgar@2.0.4~build: CWD: C:\Users\DPANtv\Desktop\ang2\test\vulgar
11 silly lifecycle vulgar@2.0.4~build: Args: [ '/d /s /c', 'npm run build:dev' ]
12 silly lifecycle vulgar@2.0.4~build: Returned: code: 1  signal: null
13 info lifecycle vulgar@2.0.4~build: Failed to exec build script
14 verbose stack Error: vulgar@2.0.4 build: `npm run build:dev`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid vulgar@2.0.4
16 verbose cwd C:\Users\DPANtv\Desktop\ang2\test\vulgar
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
19 error node v6.9.5
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error vulgar@2.0.4 build: `npm run build:dev`
22 error Exit status 1
23 error Failed at the vulgar@2.0.4 build script 'npm run build:dev'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the vulgar package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run build:dev
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs vulgar
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls vulgar
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by NickBolles** [comment]
Are you sure your on the right branch? And can you also check to see if the files are emitted to the dist/client folder?

**Comment by Mr-Black-Dahlia** [comment]
my initial clone command was: git clone -b nb/materialize (git url)

and here is what my dist/client folder looks like:

http://imgur.com/a/tLsaJ

**Comment by NickBolles** [comment]
Just to get a clean machine with no NPM cache
docker run -it node:boron bash 

Check to make sure nothing is installed
npm list
npm info it worked if it ends with ok
npm info using npm@3.10.10
npm info using node@v6.9.5
/usr/src/app
`-- (empty)

Clone the repo
git clone --progress -v "https://github.com/NickBolles/vulgar.git"

cd vulgar

Switch to the branch
git checkout -b nb/materialize remotes/origin/nb/materialize

NPM setup
npm install
npm install -g gulp


Check versions
gulp -v
[18:18:49] CLI version 3.9.1
[18:18:49] Local version 3.9.1
node -v
v6.9.5
npm -v
3.10.10

tsc -v
not found... vulgar must install typescript locally

Try building
gulp serve
 Error that there isnt a config file
 
no nano or vim, cant install through apt-get.....
example json is invalid, cant just copy
cant get a docker cp command to work...
can we copy the config example and remove the top 6 lines? YES! (maybe, we have to try running it to see)
tail -n +7 ./config/config.example.json > ./config/config.json

Try building server
gulp serve


            return self.emit('error', new MongoError(f('failed to connect to server [%s] on first connect', self.name)));
                  This is good, the server is running, it just cant connect to mongo

Build app
npm run build
Fails with error:

ERROR in [at-loader] src/server/server.spec.ts:6:3     TS2304: Cannot find name 'before'.
            This is just a typescript error that it cant find the "before" typing for mocha. This can be fixed. but the app will still run with this

**Comment by NickBolles** [comment]
Those are the steps I took. As for the branch,
Even if you clone from that URL you still have to switch branches. Because this is a fork of vulgar and isnt merged into master yet. I am going to let datatypevoid take care of that. In the mean time you can run off of this branch by switching to it though:

I do this in the step above:
`git checkout -b nb/materialize remotes/origin/nb/materialize`

Try that, then do an `npm install` and then `npm build` to build the client and `gulp build` to build the server.

**Comment by Mr-Black-Dahlia** [comment]
I will have to try the above and let you know. thanks

**Comment by Mr-Black-Dahlia** [comment]
Just tried the above and I'm still getting the error. Did a fresh clone and then switch to branch. All version numbers match yours too. I also see this now too:

http://imgur.com/a/syMSW

**Comment by NickBolles** [comment]
okay, so we are experiencing the same behaviors. This is a working build. There are just some errors with typescript typing.  you can ignore these for now and continue to use it like normal.

so you can run the webpack server with `npm start` and it will build and watch the source. Then navigate to localhost:8080 to run the app off the webpack server

then run the backend server with `gulp serve`  which will do the same, build and watch the source and restart the server every time.

I will work on fixing these issues, but honestly its not that high on my priority list. Pus they are kinda finicky things.

**Comment by Mr-Black-Dahlia** [comment]
While yes I can do npm start / gulp serve after, the page just gets stuck at loading the index. (I do see the page title/header-footer in view source)

It's ok and I understand this is just something you do in your freetime. I can always just do my own auth and make my own seed, but figured I'd give this one a shot since it has everything lol.

Thanks man. Hopefully we can figure this out one day, I really like vulgar. mean.js and meanio are just too outdated.

**Comment by NickBolles** [comment]
Do you have your database configured correctly?

check your gulp serve output to see if there are any mongoconnection errors

**Comment by NickBolles** [comment]
Hey, why don't you try this out again on the nb/development branch
https://github.com/NickBolles/vulgar/tree/nb/development

I've made a ton of additions and fixes in the last couple days, including forgotten password resets and emails to users when registering and password changes

I think I have fixed most of the issues now, there are a few janky things on the client, but other than that its working pretty good.

**Comment by Mr-Black-Dahlia** [comment]
After I finish this intense game of City Planning in Cities Skylines :p I will give it a shot and let you know. That sounds like some great additions.

**Comment by Mr-Black-Dahlia** [comment]
`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\color\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.10
3 info using node@v6.10.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle vulgar@2.0.4~prebuild: vulgar@2.0.4
6 silly lifecycle vulgar@2.0.4~prebuild: no script for prebuild, continuing
7 info lifecycle vulgar@2.0.4~build: vulgar@2.0.4
8 verbose lifecycle vulgar@2.0.4~build: unsafe-perm in lifecycle true
9 verbose lifecycle vulgar@2.0.4~build: PATH: C:\Users\color\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\color\Desktop\ang2\vulgar\node_modules\.bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Git\cmd;C:\Program Files (x86)\Heroku\bin;C:\Program Files (x86)\git\cmd;C:\Program Files (x86)\Git\cmd;C:\Program Files\nodejs\;C:\Users\color\AppData\Local\Microsoft\WindowsApps;C:\Users\color\AppData\Local\atom\bin;C:\Users\color\AppData\Roaming\npm;C:\Program Files (x86)\Microsoft VS Code\bin
10 verbose lifecycle vulgar@2.0.4~build: CWD: C:\Users\color\Desktop\ang2\vulgar
11 silly lifecycle vulgar@2.0.4~build: Args: [ '/d /s /c', 'npm run build:dev' ]
12 silly lifecycle vulgar@2.0.4~build: Returned: code: 1  signal: null
13 info lifecycle vulgar@2.0.4~build: Failed to exec build script
14 verbose stack Error: vulgar@2.0.4 build: `npm run build:dev`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\color\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\color\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid vulgar@2.0.4
16 verbose cwd C:\Users\color\Desktop\ang2\vulgar
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\color\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
19 error node v6.10.0
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error vulgar@2.0.4 build: `npm run build:dev`
22 error Exit status 1
23 error Failed at the vulgar@2.0.4 build script 'npm run build:dev'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the vulgar package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run build:dev
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs vulgar
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls vulgar
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]`

This is on my home office computer and it's looking like the same issue as my computer at work.

It's yelling something about webpack then failing there:

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\color\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:dev"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! vulgar@2.0.4 build:dev: `webpack --config config/webpack/client.dev.js --progress --profile`
npm ERR! Exit status 2

**Comment by NickBolles** [comment]
what about doing a `webpack-dev-server -v`?

**Comment by Mr-Black-Dahlia** [comment]
webpack-dev-server 2.4.1
webpack 2.2.1

**Comment by NickBolles** [comment]
try one more time, I just fixed some errors I had in my checkin process... :(
